# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 233011d764af64ed350902bed0945a262f54dfd13c449d228cae9d22de77f70edaf3eb0eb2fb4417e8908a7d2e02de9ecf2433750d9439b77440ec75d4350d7c

test:
  secret_key_base: 00a41daa9eb84e029bbc44e4c3baabe291fa26c58166c5822d40612e99554fa9e5bbfaf4197f7ed194a17e4b19ece37a7ef651d22a421f02d48962127c2d7d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
