# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing.


localhost_solr: &localhost_solr
  asf:
    url: "http://localhost:8983/solr/hrwa-asf"
  fsf:
    url: "http://localhost:8983/solr/hrwa-fsf"
  site_detail:
    url: "http://localhost:8983/solr/hrwa-fsf"

#prod
fillmore_solr: &fillmore_solr
  asf:
    url: "http://fillmore.cul.columbia.edu:8080/solr-4.7-hrwa/hrwa-asf"
  fsf:
    url: "http://fillmore.cul.columbia.edu:8080/solr-4.7-hrwa/hrwa-fsf"
  site_detail:
    url: "http://fillmore.cul.columbia.edu:8080/solr-4.7-hrwa/hrwa-fsf"

development: *fillmore_solr
test: *localhost_solr
production: *fillmore_solr

hrwa_dev: *fillmore_solr
hrwa_staging: *fillmore_solr
hrwa_test: *fillmore_solr
hrwa_prod: *fillmore_solr
