# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.  
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.  
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing. 


asf-hrwa-278: &asf-hrwa-278
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/asf-hrwa-278"

test_solr: &test_solr
  asf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-asf-unit-test"
  fsf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-fsf-unit-test"
  site_detail:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-fsf-unit-test"
  asf-hrwa-278: *asf-hrwa-278

#other
coolidge_solr: &coolidge_solr
  asf:
    url: "http://coolidge.cul.columbia.edu:8080/solr-3.6/asf"
  fsf:
    url: "http://coolidge.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://coolidge.cul.columbia.edu:8080/solr-3.6/fsf"
  asf-hrwa-278: *asf-hrwa-278

#dev
carter_solr: &carter_solr
  asf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/asf"
  fsf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/fsf"
  asf-hrwa-278: *asf-hrwa-278

#staging
harding_solr: &harding_solr
  asf:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/asf"
  fsf:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/fsf"
  asf-hrwa-278: *asf-hrwa-278

#prod
vorpal_solr: &vorpal_solr
  asf:
    url: "http://vorpal.cul.columbia.edu:8080/solr-3.6/asf"
  fsf:
    url: "http://vorpal.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://vorpal.cul.columbia.edu:8080/solr-3.6/fsf"
  asf-hrwa-278: *asf-hrwa-278
  
#prod-alt
spatha_solr: &spatha_solr
  asf:
    url: "http://spatha.cul.columbia.edu:8181/solr-3.6/asf"
  fsf:
    url: "http://spatha.cul.columbia.edu:8181/solr-3.6/fsf"
  site_detail:
    url: "http://spatha.cul.columbia.edu:8181/solr-3.6/fsf"
  asf-hrwa-278: *asf-hrwa-278

development: *vorpal_solr
test: *test_solr
production: *vorpal_solr

hrwa_dev: *vorpal_solr
hrwa_staging: *vorpal_solr
hrwa_test: *vorpal_solr
hrwa_prod: *vorpal_solr