# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.  
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.  
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing. 

development: &development
  asf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/asf"
  asf-hrwa-278:
    url: "http://carter.cul.columbia.edu:8080/solr-4/asf-hrwa-278"
  fsf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/fsf"
  
test:
  asf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-asf-unit-test"
  asf-hrwa-278:
    url: "http://carter.cul.columbia.edu:8080/solr-4/asf-hrwa-278"
  fsf:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-fsf-unit-test"
  site_detail:
    url: "http://carter.cul.columbia.edu:8080/solr-3.6/hrwa_blacklight-fsf-unit-test"

hrwa_dev: *development

hrwa_staging:
  asf:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/asf"
  asf-hrwa-278:
    url: "http://harding.cul.columbia.edu:8080/solr-4/asf-hrwa-278"
  fsf:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/fsf"
  site_detail:
    url: "http://harding.cul.columbia.edu:8080/solr-3.6/fsf"
    
hrwa_test:
  asf:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/asf"
  asf-hrwa-278:
    url: "http://harding.cul.columbia.edu:8080/solr-4/asf-hrwa-278"
  fsf:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/fsf"
  site_detail:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/fsf"

# TODO: This is temporary until we have our dedicated SOLR server
# Please note the port is 8181 and not 8080, which currently is the
# SOLR service for CLIOBeta
hrwa_prod:
  asf:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/asf"
  asf-hrwa-278:
    url: "http://harding.cul.columbia.edu:8080/solr-4/asf-hrwa-278"
  fsf:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/fsf"
  site_detail:
    url: "http://machete.cul.columbia.edu:8181/solr-3.6/fsf"
    
# The following valid_overrides section is for changing solr servers after deployment
valid_overrides:
  carter:   "http://carter.cul.columbia.edu:8080"
  coolidge: "http://coolidge.cul.columbia.edu:8080"
  harding:  "http://harding.cul.columbia.edu:8080"
  machete:  "http://machete.cul.columbia.edu:8181"